import { Proveedor } from './models';
export const proveedores: Proveedor[] = [
  {
    id: 1,
    first_name: 'Lorrayne',
    last_name: 'Rizzetti',
    enterprise: 'InnoZ',
    email: 'lrizzetti0@prlog.org',
    gender: 'Female',
    ubication: { lat: 19.241239, lng: 108.758458 },
  },
  {
    id: 2,
    first_name: 'Norby',
    last_name: 'Dumberrill',
    enterprise: 'Linklinks',
    email: 'ndumberrill1@ustream.tv',
    gender: 'Agender',
    ubication: { lat: 39.8441383, lng: 116.444208 },
  },
  {
    id: 3,
    first_name: 'Doralyn',
    last_name: 'Van Merwe',
    enterprise: 'Eire',
    email: 'dvanmerwe2@vinaora.com',
    gender: 'Female',
    ubication: { lat: 42.5530523, lng: 70.0024837 },
  },
  {
    id: 4,
    first_name: 'Jeane',
    last_name: 'Bullman',
    enterprise: 'Zoozzy',
    email: 'jbullman3@blogger.com',
    gender: 'Agender',
    ubication: { lat: 41.3743894, lng: -7.6099869 },
  },
  {
    id: 5,
    first_name: 'Ike',
    last_name: 'Kilday',
    enterprise: 'Flashdog',
    email: 'ikilday4@answers.com',
    gender: 'Female',
    ubication: { lat: 46.86436, lng: 87.71608 },
  },
  {
    id: 6,
    first_name: 'Brandea',
    last_name: 'Pancoast',
    enterprise: 'Snaptags',
    email: 'bpancoast5@indiegogo.com',
    gender: 'Male',
    ubication: { lat: 52.6545685, lng: 41.4475479 },
  },
  {
    id: 7,
    first_name: 'Maryjo',
    last_name: 'Charker',
    enterprise: 'Mydeo',
    email: 'mcharker6@timesonline.co.uk',
    gender: 'Non-binary',
    ubication: { lat: 53.175543, lng: 21.296838 },
  },
  {
    id: 8,
    first_name: 'Carlos',
    last_name: 'Geroldi',
    enterprise: 'Dablist',
    email: 'cgeroldi7@dropbox.com',
    gender: 'Male',
    ubication: { lat: 15.0541658, lng: -91.229784 },
  },
  {
    id: 9,
    first_name: 'Britni',
    last_name: 'Acory',
    enterprise: 'Livetube',
    email: 'bacory8@csmonitor.com',
    gender: 'Non-binary',
    ubication: { lat: 50.5353182, lng: 15.2594155 },
  },
  {
    id: 10,
    first_name: 'Lorianne',
    last_name: 'Mairs',
    enterprise: 'Aimbo',
    email: 'lmairs9@home.pl',
    gender: 'Agender',
    ubication: { lat: 6.2272766, lng: 1.5814235 },
  },
];
